### PR TITLE
add examples of subaccounts resource use

### PR DESCRIPTION
**Pull request by coldacid**
Completing the documentation story for subaccounts so that the readme's examples link won't be broken.

### CODE REVIEW

**Comment by aydrian** [comment]
Thanks. It looks good but can you change "SDK" to "client library"? We are trying to change all the SDK language. We refer to these as client libraries now.

**Comment by coldacid** [comment]
Sure, I'll take care of that on the train and update when I get in the office.

**Comment by aydrian** [comment]
Thanks!

**Comment by coldacid** [comment]
No problemo!

**Pull request merged**
