### PR TITLE
#92: Added gzipped response support

### PR DESCRIPTION
**Pull request by ewandennis**
- Request's gzip option now defaults to true with caller control
 - Bumped nock version to enable gzip support

### CODE REVIEW

**Comment by aydrian** [comment]
Did you do a `--save` when you npm installed the gzip library?

**Comment by ewandennis** [comment]
This pr relies on node's own zlib module - no external gzip lib required and package.json has had the nock version bumped. The failing Travis report dies while writing its coverage report in node 0.10 which isn't too clear - will attempt to repro.

**Comment by ewandennis** [comment]
I had a test that used zlib.gzipSync() which wasn't introduced until after node 0.10.  I also didn't run the Mocha test suite against node 0.10.  I just used the default grunt task which produces coverage data from the tests while sorta masking the test results themselves.

**Comment by aydrian** [comment]
LGTM

**Pull request merged**
