### PR TITLE
ISSUE-33 made transmission unit tests more unity

### LINKED ISSUE #33: Clean up transmissions unit tests
We should clean up the unit tests for the Transmissions API. We should:
 * remove unnecessary tests, e.g., `expect(method).to.be.a.function`
 * mock dependencies
 * add tests for unhappy paths and boundary conditions

### PR DESCRIPTION
**Pull request by colestrode**
I cleaned up the transmissions unit tests so that they are more truly unit tests. I removed some dead code and reorganized a little. I also added some error checking in the transmissions library. This closes #33.

### CODE REVIEW

**Comment by colestrode** [comment]
Need to bump patch version since I added the error handling in transmissions?

**Comment by aydrian** [comment]
Can you remove the require calls for SparkPost and nock from the spec file?
And while you're in the transmission.js, can you removed the commented out code in the callback?

**Comment by colestrode** [comment]
:+1:

**Comment by aydrian** [comment]
My last issue is should we check that the client is an instance of SparkPost? That would involve changing how the client is mocked in the spec.

**Comment by aydrian** [comment]
After side conversation, everything looks good.

**Pull request merged**
