### PR TITLE
Issue 45

### PR DESCRIPTION
**Pull request by bdeanindy**
This should provide a way to convert camelCase to snake_case for payload objects, just need to flush out the remaining tests for some api calls and implement it...but it should be usable.

@aydrian could you review, test this and let me know if it requires any changes.

### CODE REVIEW

**Comment by aydrian** [comment]
Remove `snake-case` from the package.json and we should be good to go.

**Comment by max-mathieu** [comment]
Fwiw, latest version of lodash comes with _.snakeCase (as well as _.kebabCase, _.camelCase, _.titleCase...)

**Comment by aydrian** [comment]
Haha... of course it does.

**Comment by bizob2828** [comment]
any reason not to merge this?

**Comment by bizob2828** [comment]
oh i see, might be better to use lodash _.snakeCase instead of handrolling this

**Comment by bdeanindy** [comment]
@bizob2828 I didn't know that lodash had that method...totally cool.

Of course while testing this last night I found a couple of edge cases that I didn't consider, I'll get those updated today and roll them into this PR:

1. Substitution Data should NOT have any sub-keys modified
2. MetaData should NOT have any sub-keys modified
3. Tags should NOT have any sub-keys modified

**Pull request merged**
