### PR TITLE
Implement promise support

### PR DESCRIPTION
**Pull request by aydrian**
#107 Used bluebird.js. You can now use a callback or a promise. All the tests still pass but we might want to look at how and what we are testing.

### CODE REVIEW

**Comment by jasonrhodes** [comment]
Probably not in scope for this ticket, so we can file a separate refactor issue (happy to help with this), but look at what happens with the core lib `fs` in node, if you pass it a function as its first argument (it expects a string path first, then a function as a second arg):

```
> fs.readFile(function(err, buffer) { console.log(arguments); });
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.readFile (fs.js:250:11)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
```

It doesn't smartly hand that error to the function provided, because it wasn't provided in the right place. So I think we can ditch a lot of this kind of extra-cautions checking, a la:

```
if(typeof domain === 'function') {
  callback = domain;
  domain = null;
}
```

and simplify a lot of this.

**Comment by jasonrhodes** [comment]
So this looks good, nice work @aydrian -- I've been looking through everything and went over the old discussions and did some testing locally. I have a file that's about 15-20 lines that can replace our `bluebird` dependency and keep all of your changes otherwise intact, with all tests passing. Are we ok with supporting nodejs 0.12.15+ with this new version (or 4.0+ even?)?

**Comment by aydrian** [comment]
Let's create another ticket for the refactor if you can generalize that issue. I'm sure it's in many places. And there's a lot yet to refactor.

I am all for discontinuing support for versions 0.10 and 0.12. I have issue #153 for that.

What is the benefit to not using bluebird? All the research I've done shows that they are more performant than native promises. http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

**Comment by aydrian** [comment]
This breaks the build for v.10 and v.12, but we will be remove support in a different ticket.

**Pull request merged**
