### PR TITLE
body might be undefined

### PR DESCRIPTION
**Pull request by mstdokumaci**
When body is undefined it throws exceptions.

### CODE REVIEW

**Comment by aydrian** [comment]
Thank you for your Pull Request. We will look it over as soon as we can.

**Comment by ewandennis** [comment]
Hi @mstdokumaci.  Many thanks for the PR.  Would you mind [opening an issue](/SparkPost/node-sparkpost/issues) describing how you ran into this problem?  It would also be great to see a matching test.  We'll then use the issue and test to know if we have another fix underway which covers this issue.

**Comment by jasonrhodes** [comment]
This is a good catch. Another solution for this since we have lodash on the page would be:
```javascript
err.errors = _.get(body, 'errors', null);
```
And `null` can be replaced with whatever we want to default errors to be.

**Comment by jasonrhodes** [comment]
@mstdokumaci thanks for this PR -- looks good, just 2 quick things:
1. Can you move the `||` check to the top of that else if block? Something like `body = body || {};` just to make it more explicit what happened there.
2. We'll need a test to cover this case. Are you comfortable adding one?

**Comment by aydrian** [comment]
Thanks for the update, @mstdokumaci. If you can add a test, I can get this into today's 1.3.0 release.

**Comment by aydrian** [comment]
I added the test and merged.

**Pull request closed without merging**
