### PR TITLE
ISSUE-77: Update Sending Domains docs and examples

### LINKED ISSUE #77: Update Sending Domains docs and examples
[sendingDomains.md](https://github.com/SparkPost/node-sparkpost/blob/master/docs/resources/sendingDomains.md) is out of date, and needs updated to reflect the API structure.

Update the following Sending Domain Examples:
- [Create](https://github.com/SparkPost/node-sparkpost/blob/master/examples/sendingDomains/create_sendingDomain.js)
- [Update](https://github.com/SparkPost/node-sparkpost/blob/master/examples/sendingDomains/update_sendingDomain.js)

### PR DESCRIPTION
**Pull request by aydrian**
Updated sending domains doc and examples for api format. Fixed callback in other docs.

Closes #77

### CODE REVIEW

**Comment by bdeanindy** [comment]
Need to fix your references to private/public to fix the build:
https://travis-ci.org/SparkPost/node-sparkpost/builds/66933204

**Comment by aydrian** [comment]
We should be all good now. I also removed a `console.log` that was left in the sendingDomains lib. Looks like there are a few tests missing from the toApiFormat function that is preventing us from achieving 100% coverage.

**Comment by bdeanindy** [comment]
Create the issues for new tests you feel are needed on toApiFormat and assign to me please.

This change looks good.

Are there any other docs which need updated?

**Comment by aydrian** [comment]
I looked but Sending Domains and Transmissions were the only ones affected by the change in toApiFormat.

**Pull request merged**
